dist: trusty
sudo: required
language: c++
compiler:
  - gcc
  - clang

branches:
  only:
  - master
  - travis

install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-regex1.54.0 libboost-regex1.54-dev cmake lcov

script:
  - chmod +x llvm_config.sh
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_TEST=ON -DWITH_COVERAGE=ON
  - sudo cmake --build .
  - sudo cmake --build . --target install
  - cd ../
  - ./llvm_config.sh
  - source build/env.sh
  - cd build && ./toolboxtest