dist: trusty
sudo: required
language: c++
compiler:
  - g++
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install cmake

script:
  - sudo sh llvm_config.sh
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_TEST=ON
  - sudo cmake --build .
  - sudo cmake --build . --target install
  - sudo sh run_test.sh