dist: trusty
sudo: required
language: c++
compiler:
  - g++
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo -s source llvm_config.sh

script:
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_TEST=ON
  - sudo cmake --build .
  - sudo cmake --build . --target install
  - cd ../ && sudo sh run_test.sh