dist: trusty
sudo: required
language: c++
compiler:
  - g++
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install cmake

script:
  - chmod +x llvm_config.sh
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_TEST=ON
  - sudo cmake --build .
  - sudo cmake --build . --target install
  - cd ../
  - ./llvm_config.sh
  - source build/env.sh
  - cd build && ./toolboxtest