dist: trusty
sudo: required
language: c++
compiler:
  - g++
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install cmake

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target toolboxpp
  - sudo cmake --build . --target install