version: 2
jobs:
  build:
    docker:
      - image: debian:jessie
    steps:
      - run: apt-get update
      - run: apt-get install -y python gcovr git cmake lcov gcc g++
      - run: git clone --recursive https://github.com/edwardstock/toolboxpp .
      - run: chmod +x llvm_config.sh
      - run: mkdir -p build
      - run: cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_TEST=ON -DWITH_COVERAGE=On -DENABLE_MULTIBYTE=Off -DPython_DIR=/usr
      - run: cmake --build ./build
      - run: cmake --build ./build --target install
      - run: ./llvm_config.sh
      - run: source build/env.sh
      - run:
          name: Testing
          command: cmake --build ./build --target toolboxtest_coverage