version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
        environment:
          CXX: /usr/bin/g++
          CC: /usr/bin/gcc
    steps:
      - run: apt-get update && apt-get install -y python python3 python3-pip gcovr git lcov gcc g++ wget
      - run: pip3 install setuptools -U
      - run: pip3 install conan
      - run: conan remote add scatter https://api.bintray.com/conan/edwardstock/scatter
      - run: conan user -p $BINTRAY_API_KEY -r scatter edwardstock
      - run: git clone --recursive https://github.com/edwardstock/toolboxpp .
      - run: $(which bash) .circleci/setup.sh
      - run: $(which bash) .circleci/test.sh
      - run: $(which bash) .circleci/deploy.sh