version: 2.1
commands:
  do_all:
    steps:
      - run: conan remote add -f edwardstock https://api.bintray.com/conan/edwardstock/conan-public
      - run: conan user -p $BINTRAY_API_KEY -r edwardstock edwardstock
      - run: git clone --recursive https://github.com/edwardstock/toolbox .
      - run: $(which bash) .circleci/setup.sh
      - run: $(which bash) .circleci/test.sh
      - run: $(which bash) .circleci/deploy.sh

jobs:
  gcc-4_8_5:
    docker:
      - image: docker.edwardstock.com/gcc_dev_el7
    steps:
      - do_all

  gcc-5:
    docker:
      - image: conanio/gcc5
        environment:
          CONAN_CPU_COUNT: 4
          TOOLBOX_USE_CONAN_BOOST: 1
    steps:
      - do_all
  gcc-6:
    docker:
      - image: conanio/gcc6
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all
  gcc-7:
    docker:
      - image: conanio/gcc7
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all
  gcc-8:
    docker:
      - image: conanio/gcc8
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all
  gcc-9:
    docker:
      - image: conanio/gcc9
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all
  gcc-10:
    docker:
      - image: conanio/gcc10
        environment:
          CONAN_CPU_COUNT: 4
    steps:
      - do_all

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - gcc-4_8_5
      - gcc-5
      - gcc-6
      - gcc-7
      - gcc-8
      - gcc-9
      - gcc-10